In [20]:
import pandas as pd
import numpy as np

In [7]:
pd.date_range('2019-01-01','2020-01-01',freq='D')  # DAY

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-12-23', '2019-12-24', '2019-12-25', '2019-12-26',
               '2019-12-27', '2019-12-28', '2019-12-29', '2019-12-30',
               '2019-12-31', '2020-01-01'],
              dtype='datetime64[ns]', length=366, freq='D')

In [8]:
pd.date_range('2019-01-01','2020-01-01',freq='2D') # 2DAYS VARIATION

DatetimeIndex(['2019-01-01', '2019-01-03', '2019-01-05', '2019-01-07',
               '2019-01-09', '2019-01-11', '2019-01-13', '2019-01-15',
               '2019-01-17', '2019-01-19',
               ...
               '2019-12-13', '2019-12-15', '2019-12-17', '2019-12-19',
               '2019-12-21', '2019-12-23', '2019-12-25', '2019-12-27',
               '2019-12-29', '2019-12-31'],
              dtype='datetime64[ns]', length=183, freq='2D')

In [9]:
pd.date_range('2019-01-01','2020-01-01',freq='3W') #3 WEEK WARIATION

DatetimeIndex(['2019-01-06', '2019-01-27', '2019-02-17', '2019-03-10',
               '2019-03-31', '2019-04-21', '2019-05-12', '2019-06-02',
               '2019-06-23', '2019-07-14', '2019-08-04', '2019-08-25',
               '2019-09-15', '2019-10-06', '2019-10-27', '2019-11-17',
               '2019-12-08', '2019-12-29'],
              dtype='datetime64[ns]', freq='3W-SUN')

In [11]:
pd.date_range('2019-01-01','2022-01-01',freq='Y') #Y MEAN YEAR

DatetimeIndex(['2019-12-31', '2020-12-31', '2021-12-31'], dtype='datetime64[ns]', freq='A-DEC')

In [12]:
pd.date_range('2019-01-01','2020-01-01',freq='M') # M MEANS MONTH

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31'],
              dtype='datetime64[ns]', freq='M')

In [13]:
pd.date_range('2019-01-01','2020-01-01',freq='T') # T MEANS MINs

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 00:01:00',
               '2019-01-01 00:02:00', '2019-01-01 00:03:00',
               '2019-01-01 00:04:00', '2019-01-01 00:05:00',
               '2019-01-01 00:06:00', '2019-01-01 00:07:00',
               '2019-01-01 00:08:00', '2019-01-01 00:09:00',
               ...
               '2019-12-31 23:51:00', '2019-12-31 23:52:00',
               '2019-12-31 23:53:00', '2019-12-31 23:54:00',
               '2019-12-31 23:55:00', '2019-12-31 23:56:00',
               '2019-12-31 23:57:00', '2019-12-31 23:58:00',
               '2019-12-31 23:59:00', '2020-01-01 00:00:00'],
              dtype='datetime64[ns]', length=525601, freq='T')

In [15]:
pd.date_range('2019-01-01','2020-01-01',freq='S')   # SECONDS

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 00:00:01',
               '2019-01-01 00:00:02', '2019-01-01 00:00:03',
               '2019-01-01 00:00:04', '2019-01-01 00:00:05',
               '2019-01-01 00:00:06', '2019-01-01 00:00:07',
               '2019-01-01 00:00:08', '2019-01-01 00:00:09',
               ...
               '2019-12-31 23:59:51', '2019-12-31 23:59:52',
               '2019-12-31 23:59:53', '2019-12-31 23:59:54',
               '2019-12-31 23:59:55', '2019-12-31 23:59:56',
               '2019-12-31 23:59:57', '2019-12-31 23:59:58',
               '2019-12-31 23:59:59', '2020-01-01 00:00:00'],
              dtype='datetime64[ns]', length=31536001, freq='S')

In [22]:
dates=pd.date_range('1/1/2019',periods=100,freq='W-SAT') # SAT MEANS SATURDAY
dates                                                    # 100 PARTS DIVDED

DatetimeIndex(['2019-01-05', '2019-01-12', '2019-01-19', '2019-01-26',
               '2019-02-02', '2019-02-09', '2019-02-16', '2019-02-23',
               '2019-03-02', '2019-03-09', '2019-03-16', '2019-03-23',
               '2019-03-30', '2019-04-06', '2019-04-13', '2019-04-20',
               '2019-04-27', '2019-05-04', '2019-05-11', '2019-05-18',
               '2019-05-25', '2019-06-01', '2019-06-08', '2019-06-15',
               '2019-06-22', '2019-06-29', '2019-07-06', '2019-07-13',
               '2019-07-20', '2019-07-27', '2019-08-03', '2019-08-10',
               '2019-08-17', '2019-08-24', '2019-08-31', '2019-09-07',
               '2019-09-14', '2019-09-21', '2019-09-28', '2019-10-05',
               '2019-10-12', '2019-10-19', '2019-10-26', '2019-11-02',
               '2019-11-09', '2019-11-16', '2019-11-23', '2019-11-30',
               '2019-12-07', '2019-12-14', '2019-12-21', '2019-12-28',
               '2020-01-04', '2020-01-11', '2020-01-18', '2020-01-25',
               '2020-02-01', '2020-02-08', '2020-02-15', '2020-02-22',
               '2020-02-29', '2020-03-07', '2020-03-14', '2020-03-21',
               '2020-03-28', '2020-04-04', '2020-04-11', '2020-04-18',
               '2020-04-25', '2020-05-02', '2020-05-09', '2020-05-16',
               '2020-05-23', '2020-05-30', '2020-06-06', '2020-06-13',
               '2020-06-20', '2020-06-27', '2020-07-04', '2020-07-11',
               '2020-07-18', '2020-07-25', '2020-08-01', '2020-08-08',
               '2020-08-15', '2020-08-22', '2020-08-29', '2020-09-05',
               '2020-09-12', '2020-09-19', '2020-09-26', '2020-10-03',
               '2020-10-10', '2020-10-17', '2020-10-24', '2020-10-31',
               '2020-11-07', '2020-11-14', '2020-11-21', '2020-11-28'],
              dtype='datetime64[ns]', freq='W-SAT')

In [23]:
a=pd.DataFrame(np.random.randn(100,4 ),index=dates,columns=['colorado','Texas','newyork','ohio'])
a                             #100 rows and 4 columns

            colorado     Texas   newyork      ohio
2019-01-05 -0.715481 -0.329686  0.069522  0.239664
2019-01-12 -0.003539  0.039506  0.019265 -1.499113
2019-01-19 -0.371297  0.637797  0.162029 -1.479118
2019-01-26 -0.052656 -1.179652 -0.396184 -1.778565
2019-02-02 -0.664509 -0.694232 -0.461617 -0.547916
2019-02-09  0.449536  0.556419 -1.514038 -0.703305
2019-02-16 -0.385923  1.093570  0.113910 -0.956258
2019-02-23 -0.917659  0.740729 -1.274062  0.183992
2019-03-02  0.002749  1.039182  1.670196  1.155649
2019-03-09 -1.006567  0.895917  0.820937  1.111189
2019-03-16 -0.597451 -1.221979 -1.109465  0.913256
2019-03-23  0.199676  2.064594 -0.907221  2.001545
2019-03-30  0.677751 -0.522772  0.093436 -0.865709
2019-04-06  1.556632 -0.503972 -0.396586 -1.128553
2019-04-13 -0.002069  0.019393  2.326711 -0.766928
2019-04-20  0.067422  0.959962 -0.713442 -0.000596
2019-04-27 -0.713768  0.354911  0.914454 -0.807055
2019-05-04  0.087758  1.655117 -1.021776  0.160921
2019-05-11  0.514321 -1.923873 -0.104186 -0.197357
2019-05-18 -0.851340 -2.045517 -2.001497  0.150170
2019-05-25 -1.131234  0.770604  0.594665 -0.284799
2019-06-01 -0.682313 -0.051894 -0.867067  0.196900
2019-06-08 -0.518287  0.473745  0.733724 -0.105970
2019-06-15  1.350929 -0.434530 -0.851034  0.380874
2019-06-22 -0.137719 -1.248506 -1.364188  0.637745
2019-06-29  0.561677 -0.163450 -0.870672 -0.306092
2019-07-06 -1.280377  0.237326  0.014378  0.514985
2019-07-13  0.294232  0.077603 -1.629635  0.649220
2019-07-20  1.001905  0.070714  0.757445 -0.358119
2019-07-27 -0.795854  1.338493  1.813276  1.620561
...              ...       ...       ...       ...
2020-05-09  0.498346 -0.232883 -1.014889 -0.751227
2020-05-16  0.718905  0.605249  0.014504  0.670668
2020-05-23  1.042512 -0.142657 -0.527079  0.486691
2020-05-30  1.760764  0.482558  1.036986  0.921965
2020-06-06  0.065670 -1.031252  0.451568  0.080497
2020-06-13 -0.237062 -1.333565  0.287575 -0.394042
2020-06-20  1.520211 -0.625700 -0.825641  0.030710
2020-06-27 -0.137159 -0.814696 -0.131697 -0.348432
2020-07-04  0.058989 -2.392098  0.580429  0.181876
2020-07-11 -0.965238 -1.097244 -0.149375  0.163269
2020-07-18  0.487601 -1.896044  0.861150 -2.734402
2020-07-25 -2.244779  1.090742  0.199207  0.729346
2020-08-01 -1.332994 -0.193993 -1.643675  0.086057
2020-08-08  0.420183  1.818803  0.083627 -0.250016
2020-08-15 -0.360571 -0.916325 -0.967405  0.189422
2020-08-22  0.387130 -0.384828 -3.394091  0.904607
2020-08-29 -0.402842 -2.146544  0.071852  0.840342
2020-09-05  0.943086 -1.144942  0.647049 -0.659490
2020-09-12 -1.208900  0.518219  0.873403 -1.104207
2020-09-19  0.318089  0.158728 -0.064017  1.493260
2020-09-26 -0.477029 -0.168102  0.331722  0.621822
2020-10-03 -0.975538 -0.813631 -1.437379 -0.237261
2020-10-10 -0.046197  0.489609  1.110347 -0.198323
2020-10-17  0.787218  1.056681  0.867269  0.980707
2020-10-24 -2.596823 -2.433714  2.352930  0.254323
2020-10-31  2.024256  0.997820 -1.221094  2.558196
2020-11-07 -0.312068  0.708389 -0.522343 -0.196846
2020-11-14  1.508187  0.329498  0.102419 -2.050796
2020-11-21 -0.702025 -1.823333  0.766857  0.514787
2020-11-28  1.624451 -0.101835  2.112150 -0.287856

[100 rows x 4 columns]

In [24]:
a.loc["2020-11-28"] #  or 2020/11/28 are used

colorado    1.624451
Texas      -0.101835
newyork     2.112150
ohio       -0.287856
Name: 2020-11-28 00:00:00, dtype: float64

In [25]:
a.loc["2020-11"]

            colorado     Texas   newyork      ohio
2020-11-07 -0.312068  0.708389 -0.522343 -0.196846
2020-11-14  1.508187  0.329498  0.102419 -2.050796
2020-11-21 -0.702025 -1.823333  0.766857  0.514787
2020-11-28  1.624451 -0.101835  2.112150 -0.287856

In [26]:
pd.date_range('2012-05-02 12:56:31',periods=5,normalize=True)

DatetimeIndex(['2012-05-02', '2012-05-03', '2012-05-04', '2012-05-05',
               '2012-05-06'],
              dtype='datetime64[ns]', freq='D')

In [29]:
date=pd.DatetimeIndex(["1/1/2000","1/2/2000","1/2/2000","1/3/2000"])
date    # DEFINE DATES

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-02', '2000-01-03'], dtype='datetime64[ns]', freq=None)

In [34]:
dup=pd.Series(np.arange(4),index=date)
dup

2000-01-01    0
2000-01-02    1
2000-01-02    2
2000-01-03    3
dtype: int32

In [35]:
dup.index.is_unique

False

In [36]:
pd.date_range(start='2012-04-01',end='2020-04-01')

DatetimeIndex(['2012-04-01', '2012-04-02', '2012-04-03', '2012-04-04',
               '2012-04-05', '2012-04-06', '2012-04-07', '2012-04-08',
               '2012-04-09', '2012-04-10',
               ...
               '2020-03-23', '2020-03-24', '2020-03-25', '2020-03-26',
               '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30',
               '2020-03-31', '2020-04-01'],
              dtype='datetime64[ns]', length=2923, freq='D')

In [39]:
pd.date_range(start='2012-04-06',end='2020-04-01',freq='W')

DatetimeIndex(['2012-04-08', '2012-04-15', '2012-04-22', '2012-04-29',
               '2012-05-06', '2012-05-13', '2012-05-20', '2012-05-27',
               '2012-06-03', '2012-06-10',
               ...
               '2020-01-26', '2020-02-02', '2020-02-09', '2020-02-16',
               '2020-02-23', '2020-03-01', '2020-03-08', '2020-03-15',
               '2020-03-22', '2020-03-29'],
              dtype='datetime64[ns]', length=417, freq='W-SUN')